remote_theme: "just-the-docs/just-the-docs"
name: Jielin Yang
author:
  github: https://github.com/j-y26
  email: jielin.yang@sickkids.ca
url: https://j-y26.github.io/j-yang/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
aux_links:
  "Pipeline Source Code":
    - "//github.com/j-y26/Epigenomic-Pipelines"
heading_anchors: true
footer_content: "Copyright &copy; 2023-2024 Jielin Yang. All rights reserved. Distributed by an <a href=\"https://opensource.org/licenses/MIT\" target=\"_blank\" rel=\"noopener\">MIT License</a>"
logo: "/docs/assets/page_logo.png"
favicon_ico: "/docs/assets/favicon.ico"
back_to_top: true
back_to_top_text: "Back to top"