remote_theme: "just-the-docs/just-the-docs"
name: Jielin Yang
author:
  github: https://github.com/j-y26
  email: jielin.yang@sickkids.ca
url: https://j-y26.github.io/j-yang/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
aux_links:
  "Pipelines on GitHub":
    - "//github.com/j-y26/Epigenomic-Pipelines"
heading_anchors: true
includes:
  before_footer: "_includes/footer.html"
logo: "/docs/assets/page_logo.png"
favicon: "/docs/assets/favicon.ico"